name: My First CI Pipeline

on:
    push:
        branches: [ "main" ]
jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name: print a gretting
              run: echo "Hello, World! My first DevOps pipeline works!"

            - name: show me the current time
              run: date



