name: Python Code Quality Pipeline

on:
    push: 
        branches: [ "main" ]
    pull_request: 
        branches: [ "main" ]

jobs:
    test-and-lint:
        runs-on: ubuntu-latest
    
        steps:

            # Step 1: Download Github repository runner
            - name: checkout repository code
              uses: actions/checkout@v4
            
            # Step 2: Install Python on Github Runner  
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-node: '3.11'

            # Step 3 : Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
              

            # Step 4 : run the testfile we created
            - name: Run tests with pytest
              run: pytest test_calculator.py

    build-docker:
       runs-on: ubuntu-latest
       needs: test-and-lint

       steps:
        - name: Checkout repository code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build docker image
          run: |
            docker build  -t my-python-app:latest .
            echo "Docker image Built success"



            






